### ISSUE TITLE
helm install error storageclass.storage.k8s.io "standard" not found

### ISSUE THREAD

**Issue by cloud-66** [kubeshark/kubeshark#1337]
**Describe the bug**
How to set parameters for creating pvc\pv ?

**Provide more information**
Installing kubeshark with helm on baremetal cluster

**To Reproduce**
1. run
```
helm template .
helm install kubeshark .
```
kubectl describe persistentvolumeclaim/kubeshark-persistent-volume-claim

![image](https://user-images.githubusercontent.com/41143306/233293255-05a3a359-c5ff-4263-aaed-13c30d1b2090.png)

**Expected behavior**
Expect having option in values to use my own pvc or pv or storageclass

**Comment by RmStorm** [comment]
I ran into the same problem and then into another one.. The PVC has to be readwritemany but the current storageclasses in my cluster don't support that. Is there a way to run kubeshark without the PVC?

**Comment by alongir** [comment]
@cloud-66 and @RmStorm, Helm support is quite new. Thanks for your feedback. We'll look into it and see what we can do.

**Comment by mertyildiran** [comment]
> I ran into the same problem and then into another one.. The PVC has to be readwritemany but the current storageclasses in my cluster don't support that. Is there a way to run kubeshark without the PVC?

@RmStorm since the `PersistentVolumeClaim` is mounted to a [`DaemonSet`](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/), it must have the `ReadWriteMany` access mode criteria. Because the worker pod as being a `DaemonSet` is spawned on each node (a worker pod per node) so the worker mounts the `PersistentVolumeClaim` from each node in the cluster. For more information, please see [**Access Modes**](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes).

If you think changing [this line](https://github.com/kubeshark/kubeshark/blob/26c9f42eba44f56af0dccba763cf93def7ff3dff/helm-chart/templates/08-persistent-volume-claim.yaml#L15) into `ReadWriteOnce` would make it still work then please see this [Stack Overflow answer](https://stackoverflow.com/a/63524679).

**Comment by mertyildiran** [comment]
@cloud-66 the `storageclass` option (and `--storageclass` flag to `tap` command) added into `config.yaml` with https://github.com/kubeshark/kubeshark/commit/38d121556c72fba93a12634af9c440d323d0b4ba

Please try [the release `40.0`](https://github.com/kubeshark/kubeshark/releases/tag/40.0)

The `values.yaml` of the Helm chart has the same `storageclass` option: https://github.com/kubeshark/kubeshark/blob/26c9f42eba44f56af0dccba763cf93def7ff3dff/helm-chart/values.yaml#L22

so it's possible to set the `storageclass` value with the command below:

```shell
helm repo add kubeshark https://helm.kubeshark.co
helm install kubeshark kubeshark/kubeshark --set 'tap.storageclass=standard'
```

**Comment by dave08** [comment]
@alongir Will it work if I just change the type to ReadWriteOnce? This is a blocker on DigitalOcean too, since they also don't support ReadWriteMany...

**Comment by alongir** [comment]
@dave08 we are working on a more holistic solution. Unfortunately we introduced the persistent volume too early without considering the ramifications. A solution is a day or two from being published.

**Comment by mertyildiran** [comment]
@rjshrjndrn we have made the PVC optional (disabled by default) as of [the release 40.2](https://github.com/kubeshark/kubeshark/releases/tag/40.2)

The `persistentstorage` field in both `config.yaml` and `values.yaml` (Helm) can be set to `true` to enable the PVC.

The flag `--persistentstorage` of `tap` command enables the PVC.
